"""Inference-specific configuration for Z-Image."""

DEFAULT_HEIGHT = 1024
DEFAULT_WIDTH = 1024
DEFAULT_INFERENCE_STEPS = 8
DEFAULT_GUIDANCE_SCALE = 0.0
DEFAULT_CFG_TRUNCATION = 1.0
DEFAULT_MAX_SEQUENCE_LENGTH = 512
